companieshouse/chs-delta-api

.dockerignore
Dockerfile
README.md
go.mod
go.sum

Dockerignore file added and updated 
Dockerfile created
Go modules updated
README updated to include new information.
**Related PR in docker-chs-development**
https://github.com/companieshouse/docker-chs-development/pull/227
https://github.com/companieshouse/chs-delta-api/pull/3
**Resolves**:
DSND-26 [https://companieshouse.atlassian.net/browse/DSND-26]

Add docker support and add docker-chs-dev to README

---

go.mod
go.sum

Bump to try resolve issue with pipeline.

bump GoConvey version to latest

---

handlers/register.go
routes.yaml

Slightly speculative PR hoping to get healthcheck working on marathon.
Built & tested locally.
Updated routes.yaml to use full chs-delta-api name.
Updated register.go to remove service from name and match
route.yaml + healthcheck

Ensure routes match for healthcheck

---

handlers/register.go
routes.yaml

update group to reference api group, not internal
Change handler url to be shorter

Change routes app name as it was incorrect

---

service_map.json

Service map added to the chs-delta-api.

Add service map to service

---

Dockerfile

Updated Dockerfile from v1.15 -> v1.16

update go to v1.16

---

apispec/api-spec.yml
apispec/officer-delta-spec.yml
apispec/schema.yml

Open API 3.0 implementation using yaml
structure implementation of all known endpoints
and schema objects

Add API specification for chs-delta-api

---

Makefile
start.sh

An env file has been created for all environments so uncommenting it's usage in the Makefile and start.sh script
DSND-29

Uncomment usage of chs-delta-api env file

---

Makefile

for use with loading API spec during validation

Add cp of apispec so that it is included in the build zip

---

handlers/register.go

- This PR adds code to the register.go file to have authentication when users do not provide API Key. When the correct key is provided then it returns the status code `200 OK` otherwise it returns error with status code `401 Unauthorised` if no key is provided or if the key is incorrect.
Resolves: DSND-88

Add authentication related code for chs-delta-api

---

apispec/officer-delta-spec.yml

Resolves issue of spec being outdated.

Add missing field and correct array to actually be an array instead of an object.

---

validation/schema_testing/officers/request_bodies/enum_error_request_body
validation/schema_testing/officers/request_bodies/max_properties_request_body
validation/schema_testing/officers/request_bodies/ok_request_body
validation/schema_testing/officers/request_bodies/required_error_request_body
validation/schema_testing/officers/request_bodies/type_error_request_body
validation/schema_testing/officers/response_bodies/enum_error_response_body
validation/schema_testing/officers/response_bodies/type_error_response_body

Fixed outdated unit tests. Added use of array for previous_names_array
array object and also added new enum field to all requests and responses
where needed.

The API Spec for officers-delta changed so unit tests needed updating.

---

README.md

- Add the different way we start  up the service in docker.

Update the Readme  to differentiate the different modes

---

apispec/charges-delta-spec.yml
validation/schema_testing/charges/request_bodies/date_length_error_request_body
validation/schema_testing/charges/request_bodies/ok_request_body
validation/schema_testing/charges/request_bodies/regex_error_request_body
validation/schema_testing/charges/request_bodies/required_error_request_body
validation/schema_testing/charges/request_bodies/type_error_request_body
validation/schema_testing/charges/response_bodies/type_error_response_body

Changed bare_trustees to bare_trustee in charges Delta API Spec

DSND-493 - Changed bare_trustees to bare_trustee in charges

---

apispec/charges-delta-spec.yml
validation/schema_testing/charges/request_bodies/date_length_error_request_body
validation/schema_testing/charges/request_bodies/ok_request_body
validation/schema_testing/charges/request_bodies/required_error_request_body
validation/schema_testing/charges/response_bodies/date_length_error_response_body
validation/schema_testing/charges/response_bodies/required_error_response_body

DSND-493 - Updates after clarifications with Companies House

DSND-493 - Updates after clarifications with Companies House

---

apispec/disqualification-delta-spec.yml

This PR adds disqualified_officer to required in the disqualification spec.
**Resolves:**
- DSND-703

Fix unknown data issue

---

apispec/disqualification-delta-spec.yml

This PR reduces min length of non-required dates to 0.
**Resolves:**
- DSND-712

Allow empty date strings

---

apispec/insolvency-delete-delta-spec.yml
validation/schema_testing/insolvency/request_bodies/delete_request_body

This PR adds character length validation to the company number in the insolvency delete spec.
**Resolves:**
- DSND-713

Add validation to insolvency company number

---

handlers/register.go

- Turn doValidationOnly off for /delta/company

DSND-1010 Turn doValidationOnly off for /delta/company

---

apispec/insolvency-delta-spec.yml

Increase Insolvency address line 1 maxLength

---

README.md
apispec/api-spec.yml
apispec/psc-statement-delta-spec.yml
config/config.go
config/config_test.go
handlers/register.go
validation/schema_testing/psc/pscStatementDeltaSchema.go
validation/schema_testing/psc/pscStatementDeltaSchema_test.go
validation/schema_testing/psc/request_bodies/ok_request_body
validation/schema_testing/psc/request_bodies/required_error_request_body
validation/schema_testing/psc/request_bodies/type_error_request_body
validation/schema_testing/psc/response_bodies/required_error_response_body
validation/schema_testing/psc/response_bodies/type_error_response_body

This PR adds a new endpoint and api spec for psc statements to the delta api:
**Resolves**
DSND-1369

Add new endpoint for psc statement delta to api paths

---

apispec/psc-delta-spec.yml

Added these values so that spec is up to date

Add BO enums to kind and add URA to spec

---

apispec/company-delta-spec.yml

added 4 new fields, parent_company_name, parent_company_number, super_secure_managing_officer_count and parent_company_number. checking if they are in the right place.

initial commit

---

apispec/officer-delta-spec.yml
validation/schema_testing/officers/response_bodies/required_error_response_body

[DSND-1960](https://companieshouse.atlassian.net/browse/DSND-1960)
[DSND-1960]: https://companieshouse.atlassian.net/browse/DSND-1960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-1960 - Make company name a required field officer delta

---

apispec/officer-delta-spec.yml
validation/schema_testing/officers/request_bodies/enum_error_request_body
validation/schema_testing/officers/request_bodies/max_properties_request_body
validation/schema_testing/officers/request_bodies/ok_request_body
validation/schema_testing/officers/request_bodies/required_error_request_body
validation/schema_testing/officers/request_bodies/type_error_request_body
validation/schema_testing/officers/response_bodies/type_error_response_body

* Updated the specs to expect external_number
* Edited the test data to reflect the new message structure

DSND-2038: Map external_number to person_number in Appointments Deltas

---

README.md
apispec/api-spec.yml
apispec/filing-history-delta-spec.yml
config/config.go
config/config_test.go
handlers/register.go
handlers/register_test.go
validation/schema_testing/filinghistory/filingHistoryDeltaSchema.go
validation/schema_testing/filinghistory/filingHistoryDeltaSchema_test.go
validation/schema_testing/filinghistory/request_bodies/valid_request.json

* Add new endpoint for filing history delta
* Add new specs to correlate delta requests from CHIPS
* Add new test cases for delta happy path
* Add ChildProperties object to specs
Resolves [DSND-2121](https://companieshouse.atlassian.net/browse/DSND-2121)
[DSND-2121]: https://companieshouse.atlassian.net/browse/DSND-2121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2121 Add happy path filing history delta

---

apispec/psc-delta-spec.yml
validation/schema_testing/pscs/response_bodies/required_error_response_body

- Removed PSC Id from required list.

made psc id not required

---

Dockerfile
Tiltfile.dev

* Update tilt dev file to search out correct ssh key
Resolves [DSND-2277](https://companieshouse.atlassian.net/browse/DSND-2277)
[DSND-2277]: https://companieshouse.atlassian.net/browse/DSND-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2277 Update the golang version used for Docker build

---

handlers/register.go

- Incorrect topic of Company exemptions delta was being used.
Resolves [DSND-2300](https://companieshouse.atlassian.net/browse/DSND-2300)
[DSND-2300]: https://companieshouse.atlassian.net/browse/DSND-2300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2300 Change to use correct Kafka topic

---

README.md
apispec/acsp-profile-delta-spec.yml
apispec/api-spec.yml
config/config.go
config/config_test.go
handlers/register.go
handlers/register_test.go
validation/schema_testing/acspprofile/acspProfileDeltaSchema.go
validation/schema_testing/acspprofile/acspProfileDeltaSchema_test.go
validation/schema_testing/acspprofile/request_bodies/fields_fail_length_constraints_request.json
validation/schema_testing/acspprofile/request_bodies/invalid_data_type_request.json
validation/schema_testing/acspprofile/request_bodies/missing_required_fields_request.json
validation/schema_testing/acspprofile/request_bodies/valid_request.json
validation/schema_testing/acspprofile/response_bodies/fields_fail_length_constraints_response.json
validation/schema_testing/acspprofile/response_bodies/invalid_data_type_response.json
validation/schema_testing/acspprofile/response_bodies/missing_required_fields_response.json

* Adds the /delta/acsp and /delta/acsp/validate endpoints.
* Spec is a first draft and may change.
[DSND-2932](https://companieshouse.atlassian.net/browse/DSND-2932)
[DSND-2932]: https://companieshouse.atlassian.net/browse/DSND-2932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2932: Add ACSP profile delta endpoint

---

apispec/acsp-profile-delta-spec.yml
validation/schema_testing/acspprofile/request_bodies/fields_fail_length_constraints_request.json
validation/schema_testing/acspprofile/request_bodies/missing_required_fields_request.json
validation/schema_testing/acspprofile/request_bodies/valid_request.json

[DSND-2932](https://companieshouse.atlassian.net/browse/DSND-2932)
[DSND-2932]: https://companieshouse.atlassian.net/browse/DSND-2932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2932: Fix sole trader details spec discrepancies

---

apispec/company-delta-spec.yml

Jira Ticket: https://companieshouse.atlassian.net/browse/PAS-966
Add 2 new corporate annotation types to spec to support ESO corporate annotations.

Added delta values for eso corporate annotation

---

apispec/filing-history-delete-delta-spec.yml
validation/schema_testing/filinghistory/request_bodies/fields_exceeds_max_length_delete_request.json
validation/schema_testing/filinghistory/request_bodies/invalid_data_type_delete_request.json
validation/schema_testing/filinghistory/response_bodies/missing_required_fields_delete_response.json

* Change required for delete endpoint in API
* Update unit tests
* Passes local testing
Resolves [DSND-3112](https://companieshouse.atlassian.net/browse/DSND-3112)
[DSND-3112]: https://companieshouse.atlassian.net/browse/DSND-3112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-3112: Make company_number a required field

---

apispec/charges-delete-delta-spec.yml
validation/schema_testing/charges/response_bodies/missing_required_fields_delete_response.json

* Required as part of strict releases, decouples from CHIPS changes
* Update unit test json
Resolves [DSND-3196](https://companieshouse.atlassian.net/browse/DSND-3196)
[DSND-3196]: https://companieshouse.atlassian.net/browse/DSND-3196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-3196: Add company_number to charges delete delta (strict)

---

apispec/insolvency-delta-spec.yml

* Change required to allow live data to pass through to downstream services
Resolves [BI-14160](https://companieshouse.atlassian.net/browse/BI-14160)
[BI-14160]: https://companieshouse.atlassian.net/browse/BI-14160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-3262: Make forename and surname not required

---

README.md
terraform/groups/ecs-service/data.tf
terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/main.tf
terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
terraform/groups/ecs-service/variables.tf
terraform/groups/ecs-service/vault-providers/approle
terraform/groups/ecs-service/vault-providers/token
terraform/groups/ecs-service/vault-providers/userpass
terraform/groups/ecs-service/vault.tf
terraform/groups/ecs-service/version

as part of: [https://companieshouse.atlassian.net/browse/JU-1626](url)
main tf code changes for the upgrade and migration of chs-delta-api to AWS ECS.

main tf code changes for ecs migration

---

ecs-image-build/apispec/psc-delta-spec.yml
validation/schema_testing/pscs/request_bodies/type_error_request_body
validation/schema_testing/pscs/response_bodies/type_error_response_body

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-637
Changes:
- Identity verification details schema added
- Unit tests updated

SIV-637 delta change for psc idv statuses

---

README.md
ecs-image-build/apispec/company-delta-spec.yml
validation/schema_testing/company/request_bodies/invalid_data_type_request.json
validation/schema_testing/company/request_bodies/valid_request.json
validation/schema_testing/company/response_bodies/invalid_data_type_error_response.json

https://companieshouse.atlassian.net/browse/LP-1085
* New 'term' field defined in delta spec
* Unit test resource files updated to test the new field data
* README updated with some further details about the repo and how to build/run tests

LP-1085 Sync LP 'term' field data from CHIPS to Mongo
