Tiltfile.dev
Add Tiltfile.dev for easier development.
Allows auto reloading / building of application on file changes.
Resolves:
DSND-26 [https://companieshouse.atlassian.net/browse/DSND-26]
=> add development mode to chs-delta-api

Makefile, config/config.go, go.sum, start.sh
Adding broker address field to config
so that the start script can successfully
load them into the application.
Remove reference to individual config per env
until we need it. For now we will rely on global env.
**Resolves**
DSND-22
=> Add Kafka broker address to config

routes.yaml
Addressing PR comments, we've changed the group on routes.yaml to be internalapi
=> Make group internal as per PR comments

Dockerfile
hadonlint complained that the copy uses a numbered target, not a nmae.
Fixed by adding AS labels to the FROM lines
hadolint complained that the COPY instruction was not preceded by a
WORKDIR instruction.
Fixed by explicitly stating the WORKDIR first.
=> Fix hadolint Docker linter issues

docs/adding-a-new-delta.md
Begin implementing a wide range of documentation which will
cover all aspects of the chs-delta-api.
This commit covers documentation for adding a new delta to the
chs-delta-api service, created inside of a new docs folder.
=> Add new delta to chs-delta-api doc implementation

docs/unit-testing-a-new-schema.md, validation/schema_testing/common/schemaUnitTesting.go, validation/schema_testing/officers/officerDeltaSchema_test.go
A document has been added to the /docs directory to help
guide developers through unit testing their schema once they have
added it to the chs-delta-api.
A change to pull common unit testing code into a common folder has been made in this PR as well. By 
moving the code into a common shared file, future developers can make use of the functions provided to significantly 
lower the amount of code needed to test their schemas.
=> Add documentation for unit testing open api shcemas

validation/chOpenApiValidator.go
use the local variable instead of the constant variable at
file level.
This will fix the LocationType coming back incorrectly.
=> Override variable name locally to stop clash with constant

apispec/officer-delta-spec.yml, validation/schema_testing/officers/officerDeltaSchema_test.go, validation/schema_testing/officers/request_bodies/enum_error_request_body, validation/schema_testing/officers/request_bodies/max_properties_request_body, validation/schema_testing/officers/request_bodies/ok_request_body, validation/schema_testing/officers/request_bodies/required_error_request_body, validation/schema_testing/officers/request_bodies/type_error_request_body, validation/schema_testing/officers/response_bodies/max_properties_response_body, validation/schema_testing/officers/response_bodies/type_error_response_body
as it wasn't the right validation type for our schema
We now use a maxProperties field set to 1 which stops the
requester providing multiple properties inside of the Identification
field.
This also fixes the issue of getting a badly formatted error back
which was a side effect of using oneOf.
=> Rework the officer-delta-spec to no longer use oneOf

services/kafkaService.go
The library used in our apps uses message distribution in Kafka
partitions as hash partitioning. Since most of the time we do not
provide Keys which are vital for hash partitioning to correctly
distribute the messages to the correct partitions. In this case we
need to either use Manual Partitioning or Round Robin Partitioning
or even we could come up with the custom partitioning strategy. In
our case, Round Robin Partitioning would be ideal as we do not care
about ordering and messages will be distributed equally to all the
partitions in a topic.
Resolves: DNSD-172
=> Change Kafka message distribution strategy

handlers/deltaHandler.go
New logs will only have 1 mention of the spec each time it is called.
=> remove duplicated log line to clear logs up

services/kafkaService.go
Previously the log line was printed regardless of whether the
callSend was successful or not. We do not print this line when the
callSend returns error.
=> Update message based on outcome of callSend

README.md, docs/logging.md
Create a logging document inside of the documentation directory of our service. This document will display notable log lines and variables which are of interest to other teams, front end support and logging tools such as Kibana.
**Resolves DSND-171**
=> Add logging structure to documentation

README.md, apispec/api-spec.yml, apispec/insolvency-delta-spec.yml, config/config.go, config/config_test.go, docs/adding-a-new-delta.md, handlers/register.go, handlers/register_test.go, validation/chOpenApiValidator.go, validation/schema_testing/insolvency/insolvencyDeltaSchema.go, validation/schema_testing/insolvency/insolvencyDeltaSchema_test.go, validation/schema_testing/insolvency/request_bodies/ok_request_body, validation/schema_testing/insolvency/request_bodies/required_error_request_body, validation/schema_testing/insolvency/request_bodies/type_error_request_body, validation/schema_testing/insolvency/response_bodies/no_request_body_error_response_body, validation/schema_testing/insolvency/response_bodies/required_error_response_body, validation/schema_testing/insolvency/response_bodies/type_error_response_body
Update the Open API Spec to handle insolvency data so that the trigger can send this data to CHS
- Added the new delta to config
- Exposed the new delta endpoint
- Added unit tests for spec validation
Resolves:
DSND-344
DSND-345
=> Create openAPI spec for Insolvency Delta

apispec/charges-delta-spec.yml, validation/schema_testing/charges/request_bodies/date_length_error_request_body
DSND-493 Increased the maxLength of notice_type fields to 50 as requested by CH
=> DSND-493 Increased the maxLength of notice_type fields to 50 as requested by CH

apispec/disqualification-delta-spec.yml, validation/schema_testing/disqualifications/request_bodies/date_length_error_request_body, validation/schema_testing/disqualifications/request_bodies/ok_request_body, validation/schema_testing/disqualifications/request_bodies/required_error_request_body, validation/schema_testing/disqualifications/request_bodies/type_error_request_body, validation/schema_testing/disqualifications/response_bodies/required_error_response_body
This PR adds the delta_at property and changes the required properties of the disqualification spec to match the mandatory fields in CHIPS.
**Resolves:**
- DSND-550
=> Update disqualification spec to match chips

README.md, apispec/api-spec.yml, apispec/insolvency-delete-delta-spec.yml, handlers/deltaHandler.go, handlers/deltaHandler_test.go, handlers/register.go, models/chsDelta.go, services/kafkaService.go, services/kafkaService_test.go, services/mocks/kafkaService_mock.go, validation/schema_testing/insolvency/insolvencyDeltaSchema_test.go, validation/schema_testing/insolvency/request_bodies/delete_request_body
This PR is to add a delete endpoint for the insolvency delta so that the delta consumer will be able to identify deletes and deserialize the content within the Kafka message, this includes adding an isDelete param to the endpoint that is then transferred to the CHS Delta AVRO object.
**Resolves**
- DSND-697
=> Add insolvency delta delete endpoint

apispec/api-spec.yml, apispec/charges-delete-delta-spec.yml, handlers/register.go, services/kafkaService.go, validation/schema_testing/charges/chargesDeltaSchema_test.go, validation/schema_testing/charges/request_bodies/delete_request_body
This PR is to add a delete endpoint for the charges delta so that the delta consumer will be able to identify deletes and deserialize the content within the Kafka message.
**Resolves**
- DSND-698
=> Add charges delta delete endpoint

apispec/api-spec.yml, apispec/disqualification-delete-delta-spec.yml, handlers/register.go, validation/schema_testing/disqualifications/disqualificationsDeltaSchema_test.go, validation/schema_testing/disqualifications/request_bodies/delete_request_body
This PR is to add a delete endpoint for the disqualification delta so that the delta consumer will be able to identify deletes and deserialize the content within the Kafka message.
**Resolves**
- DSND-674
=> Add disqualification delta delete endpoint

apispec/disqualification-delete-delta-spec.yml
This PR is to add validation to the officer id so that it cannot be blank when sending a delete request.
**DSND-674**
=> Add officer id validation

apispec/insolvency-delta-spec.yml
This pr adds mandatory validation for the practitioner forename and surname on insolvency cases sent to the delta api.
**Resolves:**
- DSND-925
=> Make practitioner forename and surname mandatory

apispec/insolvency-delta-spec.yml
This pr adds required validation to forename and surname for the insolvency practitioner appointment. This is to fix an issue where omitting the fields would allow the submission through.
**Required for:**
- DSND-925
=> Make forename/surname required insolvency practitioner fields

apispec/insolvency-delta-spec.yml
This PR removes the minimum length of the forename field to allow corporate bodies through the chs-delta-api.
**Resolves**
DSND-1200
=> remove minimum forename length check appointments field

apispec/officer-delta-spec.yml
This pr adds person_number field of type string into the Officer object for the officer-delta-spec.yml. This is required so the delta api will include the person_number in the officer-delta kafka message when the chs-delta-api officer endpoint is called with the person_number field present.
Required for:
- DSND-1400
[DSND-1400]: https://companieshouse.atlassian.net/browse/DSND-1400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added person number into Officer object

apispec/officer-delta-spec.yml, validation/schema_testing/officers/request_bodies/enum_error_request_body, validation/schema_testing/officers/request_bodies/max_properties_request_body, validation/schema_testing/officers/request_bodies/ok_request_body, validation/schema_testing/officers/request_bodies/type_error_request_body, validation/schema_testing/officers/response_bodies/required_error_response_body, validation/schema_testing/officers/response_bodies/type_error_response_body
* Status is a required field on the officer delta as every officer must be appointed to a company.
[DSND-1960](https://companieshouse.atlassian.net/browse/DSND-1960)
[DSND-1960]: https://companieshouse.atlassian.net/browse/DSND-1960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-1960: Add company name and status to officer delta

apispec/insolvency-delta-spec.yml, validation/schema_testing/insolvency/request_bodies/date_length_error_request_body, validation/schema_testing/insolvency/request_bodies/ok_request_body, validation/schema_testing/insolvency/request_bodies/required_error_request_body, validation/schema_testing/insolvency/request_bodies/type_error_request_body
This PR adds `status` as a  required field to the insolvency delta spec.
[DSND-2728](https://companieshouse.atlassian.net/browse/DSND-2728)
[DSND-2728]: https://companieshouse.atlassian.net/browse/DSND-2728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-2728: Add status field to insolvency delta spec

apispec/charges-delete-delta-spec.yml, apispec/company-delete-delta-spec.yml, apispec/disqualification-delete-delta-spec.yml, apispec/filing-history-delete-delta-spec.yml, apispec/insolvency-delete-delta-spec.yml, apispec/officer-delete-delta-spec.yml, apispec/psc-delete-delta-spec.yml, apispec/psc-exemption-delete-delta-spec.yml, apispec/psc-statement-delete-delta-spec.yml, apispec/registers-delete-delta-spec.yml, validation/schema_testing/company/request_bodies/delete_bad_request_body.json, validation/schema_testing/filinghistory/response_bodies/missing_required_fields_delete_response.json
This PR makes delta_at required on delete deltas except registers which does not have delete deltas set up in CHIPS.
[DSND-3109](https://companieshouse.atlassian.net/browse/DSND-3109)
[DSND-3109]: https://companieshouse.atlassian.net/browse/DSND-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-3109: Make delta_at required for delete deltas

apispec/disqualification-delete-delta-spec.yml, validation/schema_testing/disqualifications/request_bodies/delete_request_body
This PR adds `corporate_ind` field to the dsq delete delta spec.
[DSND-3119](https://companieshouse.atlassian.net/browse/DSND-3119)
[DSND-3119]: https://companieshouse.atlassian.net/browse/DSND-3119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-3119: Add corporate_ind to delete delta

apispec/psc-delete-delta-spec.yml, validation/schema_testing/pscs/request_bodies/delete_ok_request_body, validation/schema_testing/pscs/response_bodies/delete_error_response_body
* adds internal_id as required on the psc delta spec as needed by psc delta api to perform deletes
* makes chs-delta-api consistent with private specifications
* tested locally, works as expected. 
* Also tested via triggering psc delete deltas on staging and cidev, both contain delete deltas. 
[DSND-3113](https://companieshouse.atlassian.net/browse/DSND-3113)
[DSND-3113]: https://companieshouse.atlassian.net/browse/DSND-3113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-3113: Add internal_id as required to psc delete delta spec (strict)

apispec/psc-delete-delta-spec.yml, validation/schema_testing/pscs/request_bodies/delete_bad_request_body, validation/schema_testing/pscs/response_bodies/delete_error_response_body
* adds kind as required on the psc delta spec as needed by psc delta api to post correct messages to the stream
* makes chs-delta-api consistent with private specifications
[DSND-3113](https://companieshouse.atlassian.net/browse/DSND-3113)
[DSND-3113]: https://companieshouse.atlassian.net/browse/DSND-3113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DSND-3113: Add kind as required to psc delete delta spec (strict)

terraform/groups/ecs-service/main.tf
since migration of service to ECS there was an issue as it now sits behind Eric which CHIPS does not support at present.
adding bypass logic so that it allows those requests through with the eric bypass paths option set on that specific path.
=> adding  bypass logic as migrated service to ECS

ecs-image-build/Dockerfile
Use apk command to install curl.
Base image is an alpine image so requires `apk` instead of `apt-get`
=> Add curl to docker image

ecs-image-build/Dockerfile
Remove `apk` command which is causing build to fail.
=> Fix ECR image build
